export const GET_ACCOUNTS_LIST_KEY = 'GET_ACCOUNTS_LIST_KEY';
export const GET_ACCOUNT_DETAILS_KEY = 'GET_ACCOUNT_DETAILS_KEY';
export const GET_ACCOUNT_ALLOCATION_CHART_KEY = 'GET_ACCOUNT _ALLOCATION_CHART_KEY';
export const GET_ACCOUNT_FARM_UNITS_KEY = 'GET_ACCOUNT _FARM_UNITS_KEY';
export const GET_ACCOUNT_PARCELS_KEY = 'GET_ACCOUNT _PARCELS_KEY';