
export const GET_SUB_REGION_LIST = "GET_SUB_REGION_LIST";
export const GET_SUB_REGION_MAP = "GET_SUB_REGION_MAP";
export const POST_SUBREGION = "POST_SUBREGION";
export const PUT_SUBREGION = "PUT_SUBREGION";
export const DELETE_SUBREGION = "DELETE_SUBREGION";