export const GET_FIELD_LIST_KEY = 'GET_FIELD_LIST_KEY';
export const GET_FIELD_MAP_KEY = 'GET_FIELD_MAP_KEY';
export const GET_FIELD_LIST_KEY_BY_WAP = 'GET_FIELD_LIST_KEY_BY_WAP';
export const GET_FIELD_DETAIL_KEY_BY_WAP = 'GET_FIELD_DETAIL_KEY_BY_WAP';
export const POST_FIELD_KEY_BY_WAP = 'POST_FIELD_KEY_BY_WAP';
export const PUT_FIELD_KEY_BY_WAP = 'PUT_FIELD_KEY_BY_WAP';
export const DELETE_FIELD_KEY_BY_FIELD = 'DELETE_FIELD_KEY_BY_FIELD'
export const GET_CLIENT_CROPS = 'GET_CLIENT_CROPS'