export const GET_FIELD_LIST_KEY = 'GET_FIELD_LIST_KEY';
export const GET_FIELD_MAP_KEY = 'GET_FIELD_MAP_KEY';
export const GET_MSMTPOINT_LIST_KEY = 'GET_MSMTPOINT_LIST_KEY';
export const PUT_MSMTPOINT_FIELDS_KEY = 'PUT_MSMTPOINT_FIELDS_KEY';
export const GET_CLIENT_FIELD_MAP_KEY = 'GET_CLIENT_FIELD_MAP_KEY';
export const GET_APPORTION_METHOD_TYPE = "GET_APPORTION_METHOD_TYPE";
export const GET_MESMT_POINT_FIELD_DETAIL = "GET_MESMT_POINT_FIELD_DETAIL";