export const GET_REGION_LIST = "GET_REGION_LIST";
export const GET_SUB_REGION_LIST = "GET_SUB_REGION_LIST";
export const GET_REGION_MAP = "GET_REGION_MAP";
export const GET_SUB_REGION_MAP = "GET_SUB_REGION_MAP";