export const GET_CROPS_LIST = "GET_CROPS_LIST";
export const GET_ALL_CROP_FIELDS_LIST = "GET_ALL_CROP_FIELDS_LIST";
export const GET_ALL_CROP_FIELDS_MAP = "GET_ALL_CROP_FIELDS_MAP";
export const PUT_CROPS_FIELD = "PUT_CROPS_FIELD";
export const GET_BY_ID_CROP_FIELD = "GET_BY_ID_CROP_FIELD";