export const GET_CLIENT_LIST_KEY = 'GET_CLIENT_LIST_KEY';
export const POST_CLIENT_KEY = 'POST_CLIENT_KEY';
export const PUT_CLIENT_KEY = 'PUT_CLIENT_KEY';
export const DELETE_CLIENT_KEY = 'DELETE_CLIENT_KEY';