export const POST_REGISTRATION = 'POST_REGISTRATION';
export const POST_VALIDATE_TOKEN = 'POST_VALIDATE_TOKEN';
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGOUT = 'POST_LOGOUT';
export const PUT_ASSOCIATECLIENT = 'PUT_ASSOCIATECLIENT';