export const GET_COUNTRY_LIST_KEY = 'GET_COUNTRY_LIST_KEY';
export const GET_ADMIN_AREA_LIST_KEY = 'GET_ADMIN_AREA_LIST_KEY ';
export const GET_SUB_ADMIN_AREA_LIST_KEY  = 'GET_SUB_ADMIN_AREA_LIST_KEY';
export const GET_SUB_SUB_ADMIN_AREA_LIST_KEY = 'GET_SUB_SUB_ADMIN_AREA_LIST_KEY';
export const GET_SUB_SUB_SUB_ADMIN_AREA_LIST_KEY = 'GET_SUB_SUB_SUB_ADMIN_AREA_LIST_KEY';