export const GET_CONVEYANCE_LIST = "GET_CONVEYANCE_LIST";
export const GET_CONVEYANCE_DETAILS = "GET_CONVEYANCE_DETAILS";
export const POST_CONVEYANCE = "POST_CONVEYANCE";
export const PUT_CONVEYANCE = "PUT_CONVEYANCE";
export const DELETE_CONVEYANCE = "DELETE_CONVEYANCE";