export const GET_CONVEYANCE_LIST = "GET_CONVEYANCE_LIST";
export const GET_CONVEYANCE_DETAILS = "GET_CONVEYANCE_DETAILS";
export const POST_CONVEYANCE = "POST_CONVEYANCE";
export const PUT_CONVEYANCE = "PUT_CONVEYANCE";
export const DELETE_CONVEYANCE = "DELETE_CONVEYANCE";
export const GET_CONVEYANCE_TYPES = "GET_CONVEYANCE_TYPES";
export const GET_CONVEYANCE_PARENTS = "GET_CONVEYANCE_PARENTS";
export const GET_CONVEYANCE_MAP = "GET_CONVEYANCE_MAP";