export const GET_CUSTOMERS_OPTIONS = "GET_CUSTOMERS_OPTIONS";
export const GET_FIELD_OPTIONS = "GET_FIELD_OPTIONS";
export const POST_CUSTOMER_FIELD = "POST_CUSTOMER_FIELD";
export const PUT_CUSTOMER_FIELD = "PUT_CUSTOMER_FIELD";
export const DELETE_CUSTOMER_FIELD = "DELETE_CUSTOMER_FIELD";
export const GET_ALL_CUSTOMER_FIELD = "GET_ALL_CUSTOMER_FIELD";
export const GET_ALL_CUSTOMER_FIELD_MAP = "GET_ALL_CUSTOMER_FIELD_MAP";
export const GET_BY_ID_CUSTOMER_FIELD = "GET_BY_ID_CUSTOMER_FIELD";