import { ClientFormType } from "@/types/formTypes";

export const clientInitialValues: ClientFormType = {
  clientId: undefined,
  clientLegalHa: undefined,
  clientCountry: "",
  clientAdminArea: "",
  clientSubadminArea: "",
  clientSubsubadminArea: "",
  clientSubsubsubadminArea: "",
  clientLocality: "",
  clientPostalCode: "",
  clientPoBox: "",
  clientStreet: "",
  clientPremise: "",
  clientSubpremise: "",
  clientEmail: "",
  clientEstablished: undefined,
  clientFax: "",
  clientPhone: "",
  clientWebsite: "",
  // clientGeom: [],
  clientName: "",
  uploadFile: undefined,
}