export const GET_CUSTOMER_LIST_KEY = 'GET_CUSTOMER_LIST_KEY';
export const GET_CUSTOMER_DETAIL_KEY = 'GET_CUSTOMER_DETAIL_KEY';
export const POST_CUSTOMER_KEY = 'POST_CUSTOMER';
export const PUT_CUSTOMER = 'PUT_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'